language: python
install:
  - "pip install -r test_denorm_project/test_requirements.txt"
  - pip install tox
before_script:
  - psql -c 'create database denorm_test;' -U postgres
  - mysql -e 'create database denorm_test;'
script:
  - tox -e $TOXENV
env:
  - TOXENV=py26-django15
  - TOXENV=py26-django16
  - TOXENV=py26-django17
  - TOXENV=py26-django18
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
