language: python
install:
  - "pip install -r test_denorm_project/test_requirements.txt"
  - pip install tox
before_script:
  - psql -c 'create database denorm_test;' -U postgres
  - mysql -e 'create database denorm_test;'
script:
  - tox -e $TOXENV
env:
  - TOXENV=py26-django15-sqlite
  - TOXENV=py26-django16-sqlite
  - TOXENV=py27-django15-sqlite
  - TOXENV=py27-django16-sqlite
  - TOXENV=py27-django17-sqlite
  - TOXENV=py27-django18-sqlite
  - TOXENV=py27-django19-sqlite
  - TOXENV=py27-djangomaster-sqlite
  - TOXENV=py34-django15-sqlite
  - TOXENV=py34-django16-sqlite
  - TOXENV=py34-django17-sqlite
  - TOXENV=py34-django18-sqlite
  - TOXENV=py34-django19-sqlite
  - TOXENV=py34-djangomaster-sqlite

  - TOXENV=py26-django15-mysql
  - TOXENV=py26-django16-mysql
  - TOXENV=py27-django15-mysql
  - TOXENV=py27-django16-mysql
  - TOXENV=py27-django17-mysql
  - TOXENV=py27-django18-mysql
  - TOXENV=py27-django19-mysql
  - TOXENV=py27-djangomaster-mysql
  - TOXENV=py34-django15-mysql
  - TOXENV=py34-django16-mysql
  - TOXENV=py34-django17-mysql
  - TOXENV=py34-django18-mysql
  - TOXENV=py34-django19-mysql
  - TOXENV=py34-djangomaster-mysql

  - TOXENV=py26-django15-postgres
  - TOXENV=py26-django16-postgres
  - TOXENV=py27-django15-postgres
  - TOXENV=py27-django16-postgres
  - TOXENV=py27-django17-postgres
  - TOXENV=py27-django18-postgres
  - TOXENV=py27-django19-postgres
  - TOXENV=py27-djangomaster-postgres
  - TOXENV=py34-django15-postgres
  - TOXENV=py34-django16-postgres
  - TOXENV=py34-django17-postgres
  - TOXENV=py34-django18-postgres
  - TOXENV=py34-django19-postgres
  - TOXENV=py34-djangomaster-postgres

matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=py27-djangomaster-sqlite
    - env: TOX_ENV=py34-djangomaster-sqlite
    - env: TOX_ENV=py27-djangomaster-mysql
    - env: TOX_ENV=py34-djangomaster-mysql
    - env: TOX_ENV=py27-djangomaster-postgres
    - env: TOX_ENV=py34-djangomaster-postgres
